/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LoanContract } from "./LoanContract";

export { LoanContract__factory } from "./factories/LoanContract__factory";
